### ISSUE TITLE
Add Setup instructions

### ISSUE THREAD

**Issue by nvinayvarma189** [skit-ai/johnny#4]
Being a complete GO noob, I have cloned this repo and was trying to execute the below command from within the repository
```
$ cd johnny
$ ./johnny -input tagged_data.csv -output wav_audios/ -workers 30
```

I had to spend some time understanding GOPATH, GOROOT, and other things. I was even [trying to install this repo as a package](https://medium.com/@yussufshaikh/installing-go-modules-from-github-repository-5e381cbd5683) with `go get`

Finally, I understood that the executable present in the [releases](https://github.com/skit-ai/johnny/releases) is enough. So I thought adding the setup instructions can help another fellow GO noob.

so setup is as simple as 
```
$ wget https://github.com/skit-ai/johnny/releases/download/<version>/johnny-<verson>-linux-386.tar.gz
$ tar -xvf johnny-<version>-linux-386.tar.gz # this will give you a executable file called johnny which will be used in the next command
$ ./johnny -input tagged_data.csv -output wav_audios/ -workers 30
```

**Comment by greed2411** [comment]
i have included a new section called setup, it is not as detailed as these steps with `wget` & `tar` since these are platform specific (linux, wget, tar etc).

let's see if it is repeated again.

closing it for now.
